### ISSUE TITLE
MontyHall Project Practice # 1

### ISSUE THREAD

**Issue by syoh89** [592k/MHb#1]
@syoh5188 

### Task list
- 

- [x]  Review monty hall problem code check
- [x] Run the python
- [x] Check the result

**Comment by 592k** [comment]
check
